Vet clinic database: query and update animals table
Nessrine88/Vet-clinic-database pull request #2
Opened 2023-09-27 22:28 UTC by Nessrine88

In this milestone I have :
- Add a column species of type string to animals table.
![createColumn](https://github.com/Nessrine88/Vet-clinic-database/assets/127935111/834de0cf-6fd1-4e2b-9b70-c88ccaeb999d)
- Insert the following data:
![add data to rows](https://github.com/Nessrine88/Vet-clinic-database/assets/127935111/87761fb4-5bdb-4b24-a6cd-624086e089d1)
- update the animals table by setting the species column to unspecified
![unspecified](https://github.com/Nessrine88/Vet-clinic-database/assets/127935111/c46f2a4d-2c89-4f1c-b623-0c593ca6ded7)
- rolling back the change
![ROLLBACK](https://github.com/Nessrine88/Vet-clinic-database/assets/127935111/b1827dc3-7f0c-45ff-a362-d60aa4856f8a)
- Update the animals table by setting the species column to digimon for all animals that have a name ending in mon:
![set species to digimon](https://github.com/Nessrine88/Vet-clinic-database/assets/127935111/2cc8100f-e5f6-4041-b320-e4433ae07569)
- Update the animals table by setting the species column to pokemon for all animals that don't have species already set.
![POKEMONsPECIES](https://github.com/Nessrine88/Vet-clinic-database/assets/127935111/7b11b7d9-cc03-4e51-9b45-4b97dc8b5435)
- delete all records in the animals table, then roll back the transaction:
![delete](https://github.com/Nessrine88/Vet-clinic-database/assets/127935111/89b667a9-6512-4285-aec0-5722213c115c)
- Delete all animals born after Jan 1st, 2022.
![DELETE WITH CONDITION](https://github.com/Nessrine88/Vet-clinic-database/assets/127935111/415c3b16-2d83-4b60-9909-daba3f330a71)
- Create a savepoint for the transaction.
- Update all animals' weight to be their weight multiplied by -1.
- Update all animals' weights that are negative to be their weight multiplied by -1.
![update weight](https://github.com/Nessrine88/Vet-clinic-database/assets/127935111/01d22550-653c-424e-8221-85a4ea0e7d3a)
![ROLLBACK TO THE SAVEPOINT](https://github.com/Nessrine88/Vet-clinic-database/assets/127935111/4fc42ad6-32e7-4b01-8038-85b8bff551d1)
![make all weights positive](https://github.com/Nessrine88/Vet-clinic-database/assets/127935111/3a6b90e6-d93c-4209-899a-6a3d7fc9be4a)
**Write queries to answer the following questions:**

- How many animals are there?
- How many animals have never tried to escape?
- What is the average weight of animals?
- Who escapes the most, neutered or not neutered animals?
- What is the minimum and maximum weight of each type of animal?
- What is the average number of escape attempts per animal type of those born between 1990 and 2000?
- 
![COUNT](https://github.com/Nessrine88/Vet-clinic-database/assets/127935111/b131c604-6112-4018-ab0f-a8c33a81838b)
![number of animal never escaped](https://github.com/Nessrine88/Vet-clinic-database/assets/127935111/dbeb4dae-fbe7-4837-9f20-9c28703b10f5)

![average weight](https://github.com/Nessrine88/Vet-clinic-database/assets/127935111/7c34aa85-6a1b-48c1-8340-170c94e0d249)

![max aescape attempts](https://github.com/Nessrine88/Vet-clinic-database/assets/127935111/45824ab1-cedb-4afa-9eea-cabf39b77a62)
![min and max group](https://github.com/Nessrine88/Vet-clinic-database/assets/127935111/c848e071-d282-4f75-8100-b1d7aaba3e3f)
![avg of escape for specific date for type of animals](https://github.com/Nessrine88/Vet-clinic-database/assets/127935111/6ad0f880-cdd6-42e7-a879-8bef5bc7efd2)

2023-09-27 23:03 UTC, V-Blaze requested changes
## Hi @Nessrine88 

## Required changes 🖊️ 
# Almost there 🟡 🟦 🟨 

![almost-there](https://user-images.githubusercontent.com/107632780/229242540-644ade4a-fe15-4f4c-a38b-6ded70cc4e8b.gif)


Great work so far, You have come a long way, keep moving forward👏 👍  
You've done well implementing the project requirements, but there are still some issues I think you need to improve on. 😄 👋 


 ## Highlights
- Correct Gitflow✔
- Most queries written correctly 👋 
-  Some data inserted correctly into the database ✔

 ## Required Changes ♻️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-27 23:03 UTC, V-Blaze commented on schema.sql
> +);
- You have done well so far :+1: :+1: But there are a few changes and requirements you need to meet before moving to the next milestone. :+1: :waffle: 

- [ ] When working with databases, you don't edit an already existing file to add or remove a column in a table, you add a line of SQL to do that. In this case, you are not meant to edit the animal table and add the `species` column, you rather need to do it this way.
```sh
ALTER TABLE animals ADD species varchar(100);
```
I'll suggest you update your schema file accordingly. :wave: :smile:

2023-09-27 23:03 UTC, V-Blaze commented on data.sql
> +('Ditto', '2022-04-14', 4, TRUE, 22);
-  [ ] For this Milestone and subsequent milestones, I suggest you separate the task from the one in the previous milestone, it makes your code easier to follow and understand..

- [ ] The data you filled in here `('Plantmon', '2021-11-15', 2, TRUE, -5),` is not fully correct. According to the requirement, the weight is `-5.7`. I'll suggest you update this accordingly. :+1: :100: 
- [ ] Also the data you have here `('Boarmon', '2005-06-17', 7, TRUE, 20.4),` is not fully correct. The correct `date_of_birth` should be `2005-06-07`. I'll suggest you update this. :+1: :wave: 
- [ ] Also the data here `('Squirtle', '1993-04-02', 3, TRUE, -12.13),` is not fully correct. `neutered` should be `FALSE` according to the requirement. I'll suggest you update this. :+1: :airplane:

2023-09-27 23:03 UTC, V-Blaze commented on queries.sql
> +BEGIN;
- [ ] You have done well writing out the queries but Looking at the requirement, you are missing the first 3 queries.
- - Screenshot reference:
![Selection_009](https://github.com/Nessrine88/Vet-clinic-database/assets/107632780/49a68c70-a5bc-4340-b445-cfc79a7fedb3)
- [ ] I'll suggest you go back to the requirement, reed the instructions, and write out these queries. :100: :1st_place_medal: 

Also, remember to update the screenshot accordingly :smile: :wave:

2023-09-27 23:45 UTC, Nessrine88 commented
Changes Requested:
![image](https://github.com/Nessrine88/Vet-clinic-database/assets/127935111/c790df40-c445-4988-9651-2e5a1cdb0a2a)

2023-09-28 00:19 UTC, Felix45 approved these changes
# Approved :green_circle: 
Hi @Nessrine88, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://user-images.githubusercontent.com/52934128/163691476-087b4b9c-825b-40a3-85a1-d1bde44ffa53.gif" width="250px" />

## Highlights :heavy_check_mark: 
- [x] Good SQL query design :white_check_mark: 
- [x] Animals table created and updated correctly :white_check_mark: 
- [x] Pull request has a descriptive title and summary :white_check_mark: 
- [x] Repository has a professional readme file :white_check_mark:    

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-28 10:28 UTC, merged